//! Build script for shabda: generates the English pronunciation dictionary
//! from `data/cmudict-5k.txt` at compile time.
//!
//! The ARPABET-to-Phoneme mapping here mirrors `src/arpabet.rs` — keep both in sync.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    println!("cargo::rerun-if-changed=data/cmudict-5k.txt");

    let data = fs::read_to_string("data/cmudict-5k.txt").expect("failed to read data/cmudict-5k.txt");

    // Parse entries into (word, Vec<phoneme_expr>)
    let mut entries: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for (line_num, line) in data.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with(";;;") {
            continue;
        }

        // Format: WORD  PH1 PH2 PH3 (two-space separator)
        let Some((word, phonemes_str)) = line.split_once("  ") else {
            panic!("line {}: missing two-space separator: {line}", line_num + 1);
        };

        let word = word.trim().to_lowercase();
        let phoneme_exprs: Vec<String> = phonemes_str
            .split_whitespace()
            .map(|sym| arpabet_to_phoneme_expr(sym, line_num + 1))
            .collect();

        if phoneme_exprs.is_empty() {
            panic!("line {}: no phonemes for word '{word}'", line_num + 1);
        }

        entries.entry(word).or_insert(phoneme_exprs);
    }

    // Generate Rust source
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("generated_dict.rs");
    let mut out = fs::File::create(&dest).expect("failed to create generated_dict.rs");

    writeln!(out, "// Auto-generated by build.rs from data/cmudict-5k.txt").unwrap();
    writeln!(out, "// DO NOT EDIT — changes will be overwritten on next build.").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// {} entries", entries.len()).unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "fn generated_english_entries() -> alloc::collections::BTreeMap<alloc::string::String, alloc::vec::Vec<svara::phoneme::Phoneme>> {{"
    )
    .unwrap();
    writeln!(out, "    use alloc::string::String;").unwrap();
    writeln!(out, "    use alloc::vec;").unwrap();
    writeln!(out, "    use svara::phoneme::Phoneme;").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "    let mut m = alloc::collections::BTreeMap::new();"
    )
    .unwrap();

    for (word, phonemes) in &entries {
        let phoneme_list = phonemes.join(", ");
        writeln!(
            out,
            "    m.insert(String::from({:?}), vec![{}]);",
            word, phoneme_list
        )
        .unwrap();
    }

    writeln!(out, "    m").unwrap();
    writeln!(out, "}}").unwrap();

    eprintln!(
        "shabdakosh build: generated {} dictionary entries",
        entries.len()
    );
}

/// Converts an ARPABET symbol (possibly with stress digit) to a Rust expression string.
///
/// Mirrors the mapping in `src/arpabet.rs` — keep both in sync.
fn arpabet_to_phoneme_expr(symbol: &str, line: usize) -> String {
    let (base, stress) = strip_stress(symbol);

    let variant = match base {
        // Vowels
        "AA" => "VowelOpenA",
        "AE" => "VowelAsh",
        "AH" if stress == Some(0) => "VowelSchwa",
        "AH" => "VowelCupV",
        "AO" => "VowelOpenO",
        "AW" => "DiphthongAU",
        "AY" => "DiphthongAI",
        "EH" => "VowelOpenE",
        "ER" => "VowelBird",
        "EY" => "DiphthongEI",
        "IH" => "VowelNearI",
        "IY" => "VowelE",
        "OW" => "DiphthongOU",
        "OY" => "DiphthongOI",
        "UH" => "VowelNearU",
        "UW" => "VowelU",

        // Consonants
        "B" => "PlosiveB",
        "CH" => "AffricateCh",
        "D" => "PlosiveD",
        "DH" => "FricativeDh",
        "F" => "FricativeF",
        "G" => "PlosiveG",
        "HH" => "FricativeH",
        "JH" => "AffricateJ",
        "K" => "PlosiveK",
        "L" => "LateralL",
        "M" => "NasalM",
        "N" => "NasalN",
        "NG" => "NasalNg",
        "P" => "PlosiveP",
        "R" => "ApproximantR",
        "S" => "FricativeS",
        "SH" => "FricativeSh",
        "T" => "PlosiveT",
        "TH" => "FricativeTh",
        "V" => "FricativeV",
        "W" => "ApproximantW",
        "Y" => "ApproximantJ",
        "Z" => "FricativeZ",
        "ZH" => "FricativeZh",

        _ => panic!("line {line}: unknown ARPABET symbol '{symbol}'"),
    };

    format!("Phoneme::{variant}")
}

fn strip_stress(symbol: &str) -> (&str, Option<u8>) {
    if let Some(last) = symbol.as_bytes().last() {
        match last {
            b'0' => (&symbol[..symbol.len() - 1], Some(0)),
            b'1' => (&symbol[..symbol.len() - 1], Some(1)),
            b'2' => (&symbol[..symbol.len() - 1], Some(2)),
            _ => (symbol, None),
        }
    } else {
        (symbol, None)
    }
}
