//! Import/export for pronunciation dictionaries.
//!
//! Supports CMUdict text format (no_std compatible) and JSON (requires `json` feature).

use alloc::string::String;

use crate::dictionary::PronunciationDict;
use crate::error::{Result, ShabdakoshError};

/// Parses a CMUdict-format string into a [`PronunciationDict`].
///
/// Each non-comment line: `WORD  PH1 PH2 PH3` (two-space separator).
/// Comment lines start with `;;;` and are ignored.
///
/// # Errors
///
/// Returns [`ShabdakoshError::DictParseError`] if the format is invalid or
/// an ARPABET symbol is unrecognized.
pub fn parse_cmudict(input: &str) -> Result<PronunciationDict> {
    use crate::arpabet;

    let mut dict = PronunciationDict::new();

    for (line_num, line) in input.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with(";;;") {
            continue;
        }

        let (word, phonemes_str) = line.split_once("  ").ok_or_else(|| {
            ShabdakoshError::DictParseError(alloc::format!(
                "line {}: missing two-space separator",
                line_num + 1
            ))
        })?;

        let word = word.trim();
        let mut phonemes = alloc::vec::Vec::new();

        for sym in phonemes_str.split_whitespace() {
            let phoneme = arpabet::arpabet_to_phoneme_with_stress(sym).ok_or_else(|| {
                ShabdakoshError::DictParseError(alloc::format!(
                    "line {}: unknown ARPABET symbol '{sym}'",
                    line_num + 1
                ))
            })?;
            phonemes.push(phoneme);
        }

        if phonemes.is_empty() {
            return Err(ShabdakoshError::DictParseError(alloc::format!(
                "line {}: no phonemes for word '{word}'",
                line_num + 1
            )));
        }

        dict.insert(word, &phonemes);
    }

    Ok(dict)
}

/// Serializes a [`PronunciationDict`] to CMUdict text format.
///
/// Only base entries are exported (not user overlay entries).
/// Use [`to_cmudict_with_user`] to include user entries.
#[must_use]
pub fn to_cmudict(dict: &PronunciationDict) -> String {
    use crate::arpabet;

    let mut output = String::new();
    output.push_str(";;; Generated by shabdakosh\n");

    for (word, phonemes) in dict.entries() {
        output.push_str(word);
        output.push_str("  ");
        let symbols: alloc::vec::Vec<&str> = phonemes
            .iter()
            .filter_map(arpabet::phoneme_to_arpabet)
            .collect();
        output.push_str(&symbols.join(" "));
        output.push('\n');
    }

    output
}

/// Serializes a [`PronunciationDict`] to CMUdict text format,
/// including both base and user overlay entries.
#[must_use]
pub fn to_cmudict_with_user(dict: &PronunciationDict) -> String {
    use crate::arpabet;

    let mut output = String::new();
    output.push_str(";;; Generated by shabdakosh\n");

    // Base entries
    for (word, phonemes) in dict.entries() {
        // Skip if overridden by user entry
        if dict.user_entries().contains_key(word) {
            continue;
        }
        output.push_str(word);
        output.push_str("  ");
        let symbols: alloc::vec::Vec<&str> = phonemes
            .iter()
            .filter_map(arpabet::phoneme_to_arpabet)
            .collect();
        output.push_str(&symbols.join(" "));
        output.push('\n');
    }

    // User entries
    for (word, phonemes) in dict.user_entries() {
        output.push_str(word);
        output.push_str("  ");
        let symbols: alloc::vec::Vec<&str> = phonemes
            .iter()
            .filter_map(arpabet::phoneme_to_arpabet)
            .collect();
        output.push_str(&symbols.join(" "));
        output.push('\n');
    }

    output
}

/// Parses a JSON string into a [`PronunciationDict`].
///
/// The JSON should be a direct serialization of [`PronunciationDict`].
///
/// # Errors
///
/// Returns [`ShabdakoshError::DictParseError`] if deserialization fails.
#[cfg(feature = "json")]
pub fn from_json(input: &str) -> Result<PronunciationDict> {
    serde_json::from_str(input)
        .map_err(|e| ShabdakoshError::DictParseError(alloc::format!("JSON parse error: {e}")))
}

/// Serializes a [`PronunciationDict`] to a JSON string.
///
/// # Errors
///
/// Returns [`ShabdakoshError::DictParseError`] if serialization fails.
#[cfg(feature = "json")]
pub fn to_json(dict: &PronunciationDict) -> Result<String> {
    serde_json::to_string(dict)
        .map_err(|e| ShabdakoshError::DictParseError(alloc::format!("JSON serialize error: {e}")))
}

/// Loads a CMUdict file from the filesystem.
///
/// # Errors
///
/// Returns [`ShabdakoshError::DictParseError`] on I/O or parse failure.
#[cfg(feature = "std")]
pub fn load_cmudict_file(path: &std::path::Path) -> Result<PronunciationDict> {
    let data = std::fs::read_to_string(path)
        .map_err(|e| ShabdakoshError::DictParseError(alloc::format!("failed to read file: {e}")))?;
    parse_cmudict(&data)
}

/// Saves a [`PronunciationDict`] to a CMUdict file.
///
/// # Errors
///
/// Returns [`ShabdakoshError::DictParseError`] on I/O failure.
#[cfg(feature = "std")]
pub fn save_cmudict_file(dict: &PronunciationDict, path: &std::path::Path) -> Result<()> {
    let data = to_cmudict(dict);
    std::fs::write(path, data)
        .map_err(|e| ShabdakoshError::DictParseError(alloc::format!("failed to write file: {e}")))?;
    Ok(())
}
